"""sync_models_with_db

Revision ID: 01c03c3a2b0b
Revises: aa812e48fc9a
Create Date: 2026-07-16 09:23:30.707840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01c03c3a2b0b'
down_revision: Union[str, Sequence[str], None] = 'aa812e48fc9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'last_message_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'source_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('documents', 'source')
    op.alter_column('escalations', 'conversation_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('escalations', 'status',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('escalations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('escalations_conversation_id_fkey'), 'escalations', type_='foreignkey')
    op.create_foreign_key(None, 'escalations', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.alter_column('followups', 'conversation_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('followups', 'status',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'scheduled'::text"))
    op.alter_column('followups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('followups_conversation_id_fkey'), 'followups', type_='foreignkey')
    op.create_foreign_key(None, 'followups', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.add_column('kb_chunks', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('kb_chunks', 'language',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'ru'::text"))
    op.alter_column('kb_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('uq_document_chunk', 'kb_chunks', ['document_id', 'chunk_index'])
    op.alter_column('kb_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('kb_sources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('kb_sources_source_type_source_id_key'), 'kb_sources', type_='unique')
    op.create_unique_constraint('uq_kb_source', 'kb_sources', ['source_type', 'source_id'])
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'first_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'first_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint('uq_kb_source', 'kb_sources', type_='unique')
    op.create_unique_constraint(op.f('kb_sources_source_type_source_id_key'), 'kb_sources', ['source_type', 'source_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('kb_sources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('kb_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_document_chunk', 'kb_chunks', type_='unique')
    op.alter_column('kb_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('kb_chunks', 'language',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'ru'::text"))
    op.drop_column('kb_chunks', 'metadata')
    op.drop_constraint(None, 'followups', type_='foreignkey')
    op.create_foreign_key(op.f('followups_conversation_id_fkey'), 'followups', 'conversations', ['conversation_id'], ['id'])
    op.alter_column('followups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('followups', 'status',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'scheduled'::text"))
    op.alter_column('followups', 'conversation_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(None, 'escalations', type_='foreignkey')
    op.create_foreign_key(op.f('escalations_conversation_id_fkey'), 'escalations', 'conversations', ['conversation_id'], ['id'])
    op.alter_column('escalations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('escalations', 'status',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('escalations', 'conversation_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.add_column('documents', sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'source_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('conversations', 'last_message_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
