"""add_unique_folder_id_drive_watch

Revision ID: 3f6dc4fa9064
Revises: ee86d34b872b
Create Date: 2026-07-17 17:59:15.978797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f6dc4fa9064'
down_revision: Union[str, Sequence[str], None] = 'ee86d34b872b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_unique_constraint('uq_drive_watch_folder_id', 'drive_watch_channels', ['folder_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_drive_watch_folder_id', 'drive_watch_channels', type_='unique')

    # ### end Alembic commands ###
