"""add_drive_watch_channels

Revision ID: ee86d34b872b
Revises: b78648b1429e
Create Date: 2026-07-17 17:44:15.036829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee86d34b872b'
down_revision: Union[str, Sequence[str], None] = 'b78648b1429e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drive_watch_channels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('folder_id', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('channel_id', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('drive_watch_channels')
    # ### end Alembic commands ###
